### ISSUE TITLE
Issue with scikit-learn version

### ISSUE THREAD

**Issue by iampujan** [PragyanSubedi/MathInPython#1]
@PragyanSubedi 
On the statistics notebook, Section: c. Box plot and scatter plot,
load_boston has an import error.
ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

 It can be tested in environments with scikit-learn<1.2 or maybe the dataset from kaggle. Also, in the error, they have mentioned to use the dataset from original link this way:
 data_url = "http://lib.stat.cmu.edu/datasets/boston"
 raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
 data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
 target = raw_df.values[1::2, 2]

Also, the code below this error has not run. Please update and run all cells so that it will be easy for the viewers to understand the code and output.

**Comment by PragyanSubedi** [comment]
Commit 7170a65 should fix the issue. Thank you for raising the issue.
